# Generated by Django 2.1 on 2019-04-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190425_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='admin_rate',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
