# Generated by Django 2.1 on 2019-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_admin_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='admin_rate',
            field=models.BooleanField(default=False),
        ),
    ]
