# Generated by Django 2.1 on 2019-04-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190425_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='admin_rate',
            new_name='is_featured',
        ),
    ]
